[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "7wdX7ExMUqLZS2DiUFY6rbXAzRdyA7uK6yG5e4veFuyX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/var/home/rmrt1n/Containers/dev/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
